'use strict';


var loadUnits = function loadUnits(document) {
    var units = getUnitsData();
    document.getElementById("header").innerHTML = getHeaderHtml(units);
    document.getElementById("bookmarks").innerHTML = getBookmarksHtml(units);
    document.getElementById("units").innerHTML = getUnitsHtml(units);
}

var getHeaderHtml = function getBookmarksHtml(units) {
    var html = '';
    html += '<div class="header">';
    html += '</div>';
    return html;
};
var getBookmarksHtml = function getBookmarksHtml(units) {
    var html = '';

    units.forEach(function(unit) {
        html += '<a href="#' + unit.id + '" style="background-image:linear-gradient(to right, #272727, ' + unit.color + ')">' + unit.short + '</a>';
    });
    return html;
};

var getUnitsHtml = function getUnitsHtml(units) {
    var html = '';

    units.forEach(function(unit) {
        html += '<div id="' + unit.id + '" class="unit" style="color:' + unit.color + '">';
        html += '    <div class="column pic unit">';
        html += '        <img class="badge" src="img/units/' + unit.id + '/badge.webp" alt="' + units.id + '">';
        html += '    </div>';
        html += '    <div class="column desc unit">';
        html += '        <h1>' + unit.short + '</h1>';
        html += '        <h2>' + unit.name + '</h2>';
        html += '        <br>';
        html += '        <div class="info">' + unit.doc + '</div>';
        html += '    </div>';
        html += '</div>';
        html += '<div style="background-image:linear-gradient(to right, #272727, ' + unit.color + ')">';
        var i = 0;
        unit.ops.forEach(function(op) {
            html += '<div class="column operator">';
            html += '    <div class="column pic op">';
            html += '        <img class="avatar" src="img/ops/' + op.nick + '/avatar.webp" alt="' + op.nick + '">';
            html += '        <br>';
            html += '        <img class="fullBody" src="img/ops/' + op.nick + '/fullBody.webp" alt="' + op.nick + '">';
            html += '    </div>';
            html += '    <div class="column desc op">';
            html += '        <h2 class="op">' + op.nick + '</h2>';
            if (op.first != null) {
                html += '        <h3>' + op.first + ' ' + op.last + '</h3>';
            }
            html += '        <img class="flag" src="img/flags/' + op.flag + '.png">';
            html += '        <br>';
            if (op.side != null) {
                html += '        <img class="side" src="img/' + op.side + '.webp">';
                html += '        <div class="info">Born on ' + op.birth + ' at ' + op.place + '</div>';
                html += '        <div class="info">' + op.age + 'yo</div>';
                html += '        <div class="info">' + op.height + 'm</div>';
                html += '        <div class="info">' + op.weight + 'kg</div>';
            }
            html += '        <br>';
            html += '        <div class="info">' + op.doc + '</div>';
            html += '    </div>';
            html += '</div>';
            i++;
            if(i == 2) {
                html += '<br>';
                i = 0;
            }
        });
        html += '</div>';
    });
    return html;
};

var getUnitsData = function getUnitsData() {
    return [
        {
            id: 'SAS', color: 'rgb(144, 111, 121)', short: 'SAS', name: 'Special Air Service', doc: 'Founded in 1941, the Special Air Service (S.A.S) was a unit of the British Army during WW2. The S.A.S. moved from obscurity in 1980 when they successfully rescued hostages from the Iranian Embassy siege. Their focus is on counter terrorism, hostage rescues and covert operations.',
            ops: [
                { nick: 'Sledge', first: 'Seamus', last: 'Cowden', place: 'John o\' Groats, Scotland', birth: 'April 2', age: '35', height: '1.92', weight: '95', side: 'attacker', flag: 'gb', doc: '“Coming through!” Born in the far north of Scotland, Cowden’s military father and nurse mother moved to Inverness with him and his three siblings when he was five. His athleticism elevated him to the position of Captain of the 1998 Scotland Under-20s Rugby Union Team. Following a long family tradition of military service, Cowden joined the 3rd UK Mechanised Division of the British Army. His drive and physique suit the division’s historical nickname of “Iron Sides.” Cowden’s first assignment was in the Armoured Division where he studied engineering and specialized in upgrading the infantry combat vehicles. From there, he developed various breaching tactics. He was then recruited into the SAS, where he holds multiple records in speed and strength. An expert in mechanical, ballistic, explosive and thermal breaching strategies, Cowden is the operator to choose for quick and relatively silent destruction.' },
                { nick: 'Thatcher', first: 'Mike', last: 'Baker', place: 'Bideford, England', birth: 'June 22', age: '56', height: '1.80', weight: '72', side: 'attacker', flag: 'gb', doc: '“What you can feel, what you can touch – those are the things that are real. Everything else is just a distraction.” Baker comes from a long line of dockworkers and soldiers. At the age of eighteen he enlisted for active military duty despite family pressure to join the family trade as a stevedore. Immediately thrown into politically-charged conflicts, Baker’s performance was exemplary. Further training and another conflict gave him a Distinguished Flying Cross and Conspicuous Gallantry Cross. His keen sense of observation and decisive manner, combined with his close-quarter combat techniques, made him invaluable on VIP protection detail. With extensive field experience and proficiency in SAS tactics, Baker is a critical asset to any Rainbow operation. He has honed his expertise with protective measures and electronic counter-measures and frequently works with engineers to advance the equipment. As a Warrant Officer Class 1 (Regimental Sergeant Major) Baker serves as a respected and effective mentor to new recruits. Baker maintains his agility training, continuing abseiling, and has broken numerous mountain climbing records.' },
                { nick: 'Smoke', first: 'James', last: 'Porter', place: 'London, England (Kings Cross)', birth: 'May 14', age: '36', height: '1.73', weight: '70', side: 'defender', flag: 'gb', doc: '“Sure, I care about the environment. Immediately around me, anyway.” Though Porter wasn’t an exceptional student, aptitude tests revealed his propensity for sciences. Encouraged by faculty and his parents, he was able to follow a more unorthodox manner of education with tutors, home-schooling, and field science. He flourished in this break from formal classroom studies and quickly developed his skills in chemistry, biology, and math. Uninterested in pursuing a formal university education, Porter forged a fake ID and enlisted in the British Army. Though the rigidity of army rules wasn’t always a good fit, it was offset by the diverse range of training and experiences army life gave him. While he has been reprimanded for breaking rules, his superiors quickly recognized both his innovation and strategic perspective. He was then encouraged to join the SAS. Porter prefers to acquire knowledge and skills, such as language and music, in his own way and does not excel in a formal training capacity.' },
                { nick: 'Mute', first: 'Mark R.', last: 'Chandar', place: 'York, England    ', birth: 'October 11', age: '25', height: '1.80', weight: '74', side: 'defender', flag: 'gb', doc: '“People think my codename is because I don’t like to talk. Maybe I just don’t like you.” An exceptional and well-rounded student, Chandar was one of the youngest accepted into the University of Cambridge. He majored in electronics and computer engineering, completing an internship at a prestigious tech company where he contributed to the design and function of security system prototypes. His ingenuity caught the attention of Britain’s national security office, the Government Communications Headquarters (GCHQ). Having demonstrated acuity in code breaking, Chandar became an intelligence officer within the signals intelligence (SIGINT) unit. He continues to contribute to the applied technical research team and has recently expanded his field of study to include learning Korean.' }
            ]
        },
        {
            id: 'FBISWAT', color: 'rgb(215, 91, 43)', short: 'FBI SWAT', name: 'FBI Special Weapons and Tactics Teams', doc: 'Created in 1983, The FBI Enhanced Special Weapons and Tactics (SWAT) Teams are trained to intervene in high-risk situations. Their expertise varies from hostage rescues, aircraft hijackings, tracking fugitives, stronghold and tubular assaults, to specialized sniper operations.',
            ops: [
                { nick: 'Ash', first: 'Eliza', last: 'Cohen', place: 'Jerusalem, Israel', birth: 'December 24', age: '33', height: '1.70', weight: '63', side: 'attacker', flag: 'us', doc: '“You can never truly understand a conflict until you’ve been on both sides.” Cohen’s mother is a renowned Jewish political activist and professor while her Palestinian father is a professor of Middle Eastern Studies. Cohen was raised in Israel, excelling in Mathematics and Physics. She earned a degree in Structural Engineering at Tel Aviv University and spent a few semesters at Boston University. Cohen then enlisted in the Israeli Defense Forces (IDF). After undergoing the rigorous twenty-two month training for the elite Air Force unit, Shaldag, she served five years. Skilled in ground and airborne operations, all-weather and all-terrain navigation and reconnaissance, she was invaluable in Operation Orchard. Moving to the US to work with FBI SWAT, Cohen applied her degree in Engineering and gift in structural resistance to develop advanced demolition tactics and equipment. Along with Hebrew, Cohen is fluent in Arabic, English, French and Greek.' },
                { nick: 'Thermite', first: 'Jordan', last: 'Trace', place: 'Plano, Texas', birth: 'March 14', age: '35', height: '1.78', weight: '80', side: 'attacker', flag: 'us', doc: '“You see a wall, I see an opportunity.” Trace joined the Corps straight out of high school, making him a fourth-generation Marine. Following his first tour of Iraq, he obtained enough experience to volunteer as an explosive ordnance disposal technician. After his second tour of Iraq, Trace returned to the U.S., enrolled in university, and earned a Bachelor of Science in Chemistry. He brought his experience and skills to the FBI, where he spent a number of years as a field agent within the Hazardous Materials Response Unit. Seeking more dynamic environments, Trace transferred into FBI SWAT, where he excelled at developing new barricade protocols. He then earned a spot in Rainbow where he’s shown further interest in research and development on gadget upgrades. Trace’s hometown of Plano has a major concentration of Chinese Americans, and as such Trace has conversational level of Mandarin.' },
                { nick: 'Castle', first: 'Miles', last: 'Campbell', place: 'Sherman Oaks, California', birth: 'September 20', age: '36', height: '1.85', weight: '86', side: 'defender', flag: 'us', doc: '“Listen up, people: No one dies today. Any questions’ll just have to wait.” Miles Campbell graduated from Cal State LA with a bachelor’s degree in Criminal Justice and promptly joined the LAPD. Recruited into LAPD SWAT, Campbell excelled in tactical support and high-risk incidents. His careful application of dynamic and deliberate entries made him a Captain early on, while his exceptional perimeter control earned him his first commendation. Always interested in the safety of his team, Campbell worked tirelessly to perfect defense and reinforcement techniques and equipment. He has earned multiple commendations since his first and is a certified firearms specialist. Transferred to the FBI as a field agent where he trained with the German Federal Police (GSG-9), he was then recruited into the FBI SWAT team. Campbell has participated in cross-departmental training sessions with international law enforcement agencies, including the SAS and GIGN.' },
                { nick: 'Pulse', first: 'Jack', last: 'Estrada', place: 'Goldsboro, North Carolina', birth: 'October 11', age: '32', height: '1.88', weight: '85', side: 'defender', flag: 'us', doc: '“The heart is just a motor. Like any machine, it can be fine-tuned.” Born on Seymour Johnson Air Force Base, Estrada was raised on bases across the US and internationally, in Germany, Turkey, and Japan. His father was a pilot and his mother was a classified Senior Intelligence Officer. Estrada demonstrated acumen for science at an early age and was quickly moved into an advanced curriculum. His focus on Forensic Science and Biochemistry made him a perfect fit for the Biometrics Program with the FBI, which he joined as their youngest intern. He secured his role as an agent and was soon recruited into SWAT, working both in the field and in the FBI Lab. Estrada’s high emotional intelligence led him to join the FBI’s Hostage Rescue Team (HRT) where he excelled in crisis management and negotiation tactics. His knowledge of behavioral biometrics led to the creation of the Cardiac Sensor, along with several other prototypes which he continues to refine.' }
            ]
        },
        {
            id: 'GIGN', color: 'rgb(27, 54, 82)', short: 'GIGN', name: 'Groupe d\'intervention de la Gendarmerie nationale', doc: 'The National Gendarmerie Intervention Group (GIGN) created in 1973, specializes in counter-terrorist and rescue operations. They\'ve taken part in over 1000 operations and have been selected by the ICAO to teach other member states Spec Ops hostage-rescue exercises abroad planes.',
            ops: [
                { nick: 'Twitch', first: 'Emmanuelle', last: 'Pichon', place: 'Nancy, Meurthe-et-Moselle, France', birth: 'October 12', age: '28', height: '1.68', weight: '58', side: 'attacker', flag: 'fr', doc: '“Machine learning and teamwork have one thing in common: Always lead by example.” Pichon grew up in a family of academics in the historic city of Nancy, France, where the children were encouraged to excel in Math, Science, and Technology. Early participation in sponsored computer programming competitions led to her joining the army cadets at sixteen. Almost immediately her talent was recognized, particularly in robotics. Her superiors quickly encouraged Pichon to study engineering while continuing her career in the military. From the start, Pichon’s focus has been on adaptable technology that aids soldiers in the field. While there is much praise for her technological achievements, Pichon’s tactical prowess and ability to problem solve quickly and efficiently make her a crucial operational asset. Pichon\'s unique combination of talents made her well-suited for GIGN and, later, Rainbow. She is fluent in French, English, and German and her current research focus is AI.' },
                { nick: 'Montagne', first: 'Gilles', last: 'Touré', place: 'Bordeaux, Gironde, France', birth: 'October 11', age: '48', height: '1.90', weight: '90', side: 'attacker', flag: 'fr', doc: '“Every conflict is an iteration upon the last. Every scar, a victory.” Touré began his career in law enforcement as a uniformed police officer with the National Gendarmerie. They used his imposing form whenever there was a need to show a strong police presence, earning him a spot in the Mobile Gendarmerie where the focus was on crowd control as well as military and counter-terrorism patrol missions. Touré’s push for extensive training provided him with a broad skillset and earned him a position in the GIGN. Though he’s best utilized for his breaching techniques, Touré also has training in combat engineering and reconnaissance. When not deployed with Rainbow, Touré is an instructor at GIGN.' },
                { nick: 'Doc', first: 'Gustave', last: 'Kateb', place: 'Paris, France', birth: 'September 16', age: '39', height: '1.77', weight: '74', side: 'defender', flag: 'fr', doc: '“My job is to keep you alive. Make it as hard as you like.” Of Algerian and French descent, Kateb grew up in an affluent family in Paris’ 16th arrondissement. He comes from a well-respected lineage in both the military and medicine. In his second year of medical studies with the prestigious Université Paris Descartes, Kateb answered the appeal for volunteers in Médecins Sans Frontières (MSF). He has subsequently volunteered numerous times on emergency frontline aid missions around the world. Upon graduation, Kateb declined a prominent private medical practice in favor of a career with the French Defense Health Service. Kateb’s main discipline is toxicology and ecotoxicology. He has authored studies on biological agents and their effects on at-risk populations and damaged environments, and contributed reports to the European Centre for Disease Prevention and Control (ECDC). Recognizing the ongoing need for doctors, Kateb continues to volunteer with MSF. He is a highly regarded medical officer for the commandement des forces spéciales Terre.' },
                { nick: 'Rook', first: 'Julien', last: 'Nizan', place: 'Tours, Indre-et-Loire, France', birth: 'January 6', age: '27', height: '1.75', weight: '72', side: 'defender', flag: 'fr', doc: '“If you\'re going to get shot, you may as well do it right.” Nizan’s father is a respected stone mason while his mother held numerous jobs. They both informed his sense of architectural design and precision, helping him earn top rankings in school. Along with Nizan’s intellectual interests, he excelled in athletics from an early age, including Track & Field, fencing, and cycling. He later dropped out of university to cycle across France before returning and joining the Gendarmerie. Nizan thrived in his training, which included specialized qualifications in weapons, surveillance, and criminal investigations. His adaptability put him at the top of the list in military and defense courses, quickly catching the attention of the GIGN. His first operations with that unit combined all of the elements to satisfy his endless pursuit of challenges and adventure, according to staff psychologists. Specializing in hostage rescue and surveillance, Nizan’s list of successful interventions is extensive.' },
                { nick: 'Lion', first: 'Olivier', last: 'Flament', place: 'Toulouse, Occitanie, France', birth: 'August 29', age: '31', height: '1.85', weight: '87', side: 'attacker', flag: 'fr', doc: '“Confusing what is right with what is easy can lead down a dangerous path.” When Flament’s rebellious antics landed him in hospital, disowned by his family and on the brink of homelessness, he enlisted with the French Armed Forces in an attempt to gain control of his life. Early reports flagged Flament’s skills and aptitude as well-suited for specific training in CBRN. The additional structure and strict discipline of advanced training allowed him to excel and he was quickly recruited into the 2nd Dragoon Regiment, where he worked primarily with their environmental monitoring sensors. Flament showed a fascination for bacteriology and virology, specifically vector control. Recognizing that his abilities could be better applied elsewhere, he resigned from the army and joined the Gendarmerie, with a view towards the GIGN’s Operational Support Force (FAO). His ability to remain focused and perform precise tasks under stressful conditions caught the attention Specialist Melnikova during a joint mission in Nigeria, who recommended him as a candidate for Rainbow.' }

            ]
        },
        {
            id: 'SPETSNAZ', color: 'rgb(170, 21, 18)', short: 'SPETSNAZ', name: 'Spetsial\'noïe Naznatchéniyé', doc: 'Created in 1974, Spetsnaz are members of Russian units dedicated to counter-terrorism, paramilitary and covert operations. They\'re tasked with protecting Russia\'s strategic installations, both domestic and international, though little is known is about the exact nature of their mission.',
            ops: [
                { nick: 'Glaz', first: 'Timur', last: 'Glazkov', place: 'Vladivostok, Primorsky Krai, Russia (Russian SFSR, Soviet Union)', birth: 'July 2', age: '30', height: '1.78', weight: '79', side: 'attacker', flag: 'ru', doc: '“Imagination keeps you alive. It’s how you find your way out of the dark. That, and a flashlight.” Timur “Glaz” Glazkov’s formidable skill as a sniper served him well within Spetsnaz. He has an exceptional talent for observation and attention to detail. Glazkov grew up in the seaport city of Vladivostok, where he studied art. In 2004, militants took a school hostage in Beslan resulting in the deaths of numerous people, including children. This motivated Glaz to join the Ground Forces of the Russian Federation. While training at the prestigious Khabarovsk Military Commanders Academy he developed unparalleled marksmanship and was immediately recruited into the 45th Guards Regiment. Assigned to special ops and VIP protection detail, reports consistently show that Glaz possesses a unique creative approach to problem-solving. He is the squad member with the most expertise in long-range scoped weaponry.' },
                { nick: 'Fuze', first: 'Shuhrat', last: 'Kessikbayev', place: 'Samarkand, Uzbekistan (Uzbek SSR, Soviet Union)', birth: 'October 12', age: '34', height: '1.80', weight: '80', side: 'attacker', flag: 'ru', doc: '“Chaos is only an enemy if you’re unable to adapt.” Growing up in a military family in Samarkand, Uzbekistan, Shuhrat Kessikbayev immigrated to Russia shortly before the fall of the Soviet Union. From an early age Kessikbayev displayed an aptitude for science. His interest in mechanical engineering was honed in the military where he also trained as a machinist. Kessikbayev has applied these skills in numerous engineering projects, including his own weapon, and his ability to improvise in the field with scrap materials and minimal tools has made him a legend among his fellow recruits. This is one of the key reasons he is an asset to Rainbow Operations. During his time in the 27th Motor Rifle Brigade he excelled as a sharpshooter and has extensive weapon knowledge. Deployment within the Spetsnaz is confirmed, however, all operation details remain classified. Kessikbayev is fluent in Uzbek, Russian, Ukrainian, and English.' },
                { nick: 'Kapkan', first: 'Maxim', last: 'Basuda', place: 'Kovrov, Vladimir Oblast, Russia (Russian SFSR, Soviet Union)', birth: 'May 14', age: '38', height: '1.80', weight: '80', side: 'defender', flag: 'ru', doc: '“There are many different kinds of cunning. Fortunately, survival requires only one.” Maxim “Kapkan” Basuda and his brothers grew up in Kovrov, surrounded by the influence of the Russian military. Both parents worked in the military support factories, his father in mechanical engineering and his mother in textiles. Encouraged by his parents and teachers, Basuda joined the Ministry of Internal Affairs as a police officer. Along with the standard training of weapon expertise, protection detail, and high speed pursuit, Basuda showed adroit skills with hostage rescue and information gathering. Clever strategies and self-sufficiency meant that Basuda was perfect for an undercover operation in the port town of Naryan Mar on the Barents Sea. His successful efforts to shut down organized crime prompted his recruitment into the highly respected Spetsnaz. Basuda became an avid hunter and trapper during his time in the Arctic Circle, before being transferred to Beslan in 2002.' },
                { nick: 'Tachanka', first: 'Alexsandr', last: 'Senaviev', place: 'Saint Petersburg, Russia (Leningrad, Russian SFSR, Soviet Union)', birth: 'November 3', age: '48', height: '1.83', weight: '86', side: 'defender', flag: 'ru', doc: '“They told me I’d died. They were wrong. I was reborn.” Many of the men in the Senaviev family served in the Red Army. At the age of eighteen, Senaviev was conscripted into military service just as the Soviet Union was ending its operations in Afghanistan. Upon the dissolution of his draft, Senaviev opted to enlist full time. He was part of the wrestling league, where his formidable frame and match strategy earned him accolades. Along with heavy artillery, Senaviev\'s training focused on defensive and breaching tactics, and while there he apprenticed as a precision tool and die machinist in the weapons division. Senaviev applied for a transfer to the Russian Navy but for classified reasons remained in the Armed Forces.' },
                { nick: 'Finka', first: 'Lera', last: 'Melnikova', place: 'Gomel, Belarus', birth: 'June 7', age: '27', height: '1.71', weight: '68', side: 'attacker', flag: 'ru', doc: '“The hand you get dealt isn’t the one you have to keep.” Born north of Chernobyl in Gomel, Belarus, Melnikova grew up around people already suffering from birth defects. Driven by her own childhood illness and that of those around her, Melnikova grew up determined to find a cure. She studied Cytology and Genetics at Novosibirsk State University, graduating with a PhD in Molecular Biology. She remained at NSU in the Biotechnology and Virology Laboratory, collaborating remotely with the Research Institute of Fundamental and Clinical Immunology to research treatments for a variety of pathogens and neuropathies, including her own. Melnikova’s ground-breaking research into self-driven monomer motors continues to advance medical science and military technology. Her research directly saved Spetsnaz operators from hazardous materials, resulting in an Order of Honour that opened her eyes to new possibilities. She joined the Army and became the Spetsnaz CBRN Specialist. Melnikova stands out as the go-to biological warfare expert in CTU joint exercises.' },
            ]
        },
        {
            id: 'GSG9', color: 'rgb(248, 168, 40)', short: 'GSG 9', name: 'Grenzschutzgruppe 9', doc: 'After the 1972 Munich Massacre, GSG 9 was formed to combat the growing threat of terrorism. Due to a problematic military history, GSG 9 grew from the German Federal Border Guard Service/Police. GSG 9 specializes in mitigating crisis situations, such as hostage-taking, kidnapping, terrorism, and extortion.',
            ops: [
                { nick: 'Blitz', first: 'Elias', last: 'Kötz', place: 'Bremen, Germany (West Germany)', birth: 'April 2', age: '37', height: '1.75', weight: '75', side: 'attacker', flag: 'de', doc: '“I don’t like photos of myself. The lighting is always wrong.” Kötz is a graduate of Hermann-Böse-Gymnasium, an elite academy specializing in science and language studies. Throughout his education Kötz excelled both academically and athletically. Among his many unique qualities, Kötz is multilingual with the ability to grasp the nuance of a language quickly. His physically imposing frame and skill with his weapon make him formidable in tight space, room-to-room deployment. It’s his tactical experience that secures him as a solid Rainbow elite. These abilities combined with his specialized academic background and good-natured personality make him highly sought after. He easily transitioned from a Schnelle Kräfte soldier in Kosovo to a member of GSG 9. Kötz has been integral to fostering training practices and good will between India’s National Security Guard and GSG 9.' },
                { nick: 'IQ', first: 'Monika', last: 'Weiss', place: 'Leipzig, Saxony, Germany (East Germany)', birth: 'August 1', age: '38', height: '1.75', weight: '70', side: 'attacker', flag: 'de', doc: '“Life is the ultimate Rube Goldberg machine.” Weiss’s mother is a renowned mathematician and her father is an inventor whose high academic standards encouraged Weiss and her siblings to win numerous awards in math, science, and music throughout their school years. Thriving in the gifted program enabled Weiss to complete her first internship with a local tech company at the age of sixteen. She was invited to MIT, where she focused on electrical engineering, achieving accolades for her research in Microelectronics. Weiss then joined CalTech for graduate studies in experimental electrical engineering. Weiss returned to Germany to work with military technology research before joining the Bundespolizei (BPOL) as an officer. Both the physical and mental challenges of the job appealed to Weiss and she quickly moved through the ranks. After two years with the BPOL she was recruited by the GSG 9.' },
                { nick: 'Jäger', first: 'Marius', last: 'Streicher', place: 'Düsseldorf,NRW, Germany (West Germany)', birth: 'March 9', age: '39', height: '1.80', weight: '64', side: 'defender', flag: 'de', doc: '“Birthdays. Proposals. These should be surprises. No one wants a grenade to the face.” Raised by his uncle, a mechanic with the Bundespolizei (BPOL) Aviation Group, Streicher was around engines and motors at an early age. While he demonstrated skills in mechanics, it didn’t hold the challenge that he was looking for. Since he had an affinity for complex machinery, his uncle encouraged him to study aeronautical engineering at university, but strict academic form was an uncomfortable fit for him. So while Streicher’s grades were acceptable, he had a tendency toward restless antics. Following his hobby and passion in flying, he spent considerable time around pilots and aircraft. Private corporations sought him out, but Streicher joined BPOL-Aviation Group because it offered him unique challenges, the opportunity to fly and to serve his country. Almost immediately, Streicher began designing defensive weapon systems for BPOL including a ground-based Active Defense System (ADS) prototype. It was this prototype that caught the attention of GSG 9 and Rainbow.' },
                { nick: 'Bandit', first: 'Dominic', last: 'Brunsmeier', place: 'Berlin, Germany (East Germany)', birth: 'August 13', age: '42', height: '1.80', weight: '68', side: 'defender', flag: 'de', doc: '“Survival is all about timing. Nature doesn’t give second chances.” Brunsmeier and his twin brother were raised in a working class district near the Berlin Wall. Their father worked in the police force and strongly encouraged them to join. While working with Bundespolizei (BPOL) Brunsmeier excelled in crisis situations. He transferred to the Aviation Group long enough to obtain his helicopter license but his adaptability and experience with border surveillance flagged him for undercover operations. He was embedded as an undercover agent in the terrorist organization Red Army Faction (RAF) and later in the Hannover Chapter of the Hell’s Angels. In both operations Brunsmeier’s contribution was critical in seeing key members arrested and providing valuable information. While undercover, Brunsmeier honed skills in guerrilla tactics and improvised explosive devices. He developed prototypes of his electrified barricade and deployable shield. He is fluent in German, English, Polish and Turkish.' }
            ]
        },
        {
            id: 'JTF2', color: 'rgb(17, 126, 163)', short: 'JTF2', name: 'Joint Task Force 2', doc: 'Due to public concern over the RCMP SERT police officers being taught to use primarily lethal means, the Joint Task Force 2 (JTF2) was activated in 1992. The Government of Canada does not comment on JTF2 and much of the information regarding the unit is classified.',
            ops: [
                { nick: 'Buck', first: 'Sébastien', last: 'Côté', place: 'Montreal, Quebec', birth: 'August 20', age: '36', height: '1.78', weight: '78', side: 'attacker', flag: 'ca', doc: '“There are many different kinds of cunning. Fortunately, survival requires only one.” Maxim “Kapkan” Basuda and his brothers grew up in Kovrov, surrounded by the influence of the Russian military. Both parents worked in the military support factories, his father in mechanical engineering and his mother in textiles. Encouraged by his parents and teachers, Basuda joined the Ministry of Internal Affairs as a police officer. Along with the standard training of weapon expertise, protection detail, and high speed pursuit, Basuda showed adroit skills with hostage rescue and information gathering. Clever strategies and self-sufficiency meant that Basuda was perfect for an undercover operation in the port town of Naryan Mar on the Barents Sea. His successful efforts to shut down organized crime prompted his recruitment into the highly respected Spetsnaz. Basuda became an avid hunter and trapper during his time in the Arctic Circle, before being transferred to Beslan in 2002.“Follow me. I know a shortcut.” Côté comes from a long line of military veterans and served in the Canadian Reserves throughout university. After graduating with a degree in Criminology, he enlisted full time in the Canadian Armed Forces and was assigned to the Military Police. His specialized training in high-risk situations, both long- and close-range, marine rescue, and armed ship boarding made him a strong candidate for the RCMP Emergency Response Team. Even after his acceptance into the world-renowned special operations force JTF2, Côté has continued to expand his repertoire of skills, including high-speed tactical driving on both land and water, hazardous materials management, and hostage rescue. When under stress, he exhibits self-discipline and adaptive thinking. His friendly and intuitive leadership style makes him one of the more flexible team members. Along with French and English, Côté speaks fluent Pashto and is currently enrolled in Kanien\'kéha (Mohawk) studies for personal interest.' },
                { nick: 'Frost', first: 'Tina', last: 'Lin Tsang', place: 'Vancouver, British Colombia', birth: 'May 4', age: '32', height: '1.72', weight: '63', side: 'defender', flag: 'ca', doc: '“There are two things the human body needs most in a survival situation: Water, and hope.” Tsang was raised in Vancouver, British Columbia, and enlisted with the Royal Canadian Air Force (RCAF) on her eighteenth birthday. At the Royal Military College of Canada (RMC), she graduated top of her class. Upon completion of her bachelor’s degree and officer training, Tsang was stationed on Canada’s west coast at CFB Esquimalt with the Joint Rescue Coordination Centre Victoria (JRCC Victoria). From there she served on the primary Search & Rescue response team covering BC and the Yukon Territory. Tsang has been praised for exceptional situational awareness and is valued for her mission planning and threat reaction. Her SAR training in mountain-climbing, parachuting and diving extends into her recreational time. Drawing on her background in Mechanical Engineering, Tsang helped design and modify the Sterling Mk2 LHT, or “Welcome Mat,” whose portable design allows for discreet deployment in a variety of areas and environments.' }
            ]
        },
        {
            id: 'NAVYSEALS', color: 'rgb(206, 160, 36)', short: 'NAVY SEALS', name: 'Sea, Air and Land', doc: 'Commissioned in 1942, the Amphibious Scouts and Raiders saw combat in November 1942 during Operation Torch. Comprised of small highly trained teams, this group would evolve into the NAVY SEAL, who get their name from the environments in which they operate: sea, air and land.',
            ops: [
                { nick: 'Blackbeard', first: 'Craig', last: 'Jenson', place: 'Bellevue, Washington', birth: 'March 12', age: '32', height: '1.80', weight: '84', side: 'attacker', flag: 'us', doc: '“I’m a diver. We’re used to seeing threats through a layer of tempered glass.” Instead of following the family tradition in the medical sciences, Jenson joined the US Navy. His early years in the Boy Scouts and the United States Naval Sea Cadet Corps (Blue Angels Squadron) solidified his desire to serve his country and see the world. Joining the military offered him the ideal opportunity to pursue an academic education while learning a wide range of skills that fueled his adventurous spirit. After his initial military stint, Jenson focused on the US Navy SEALs as his ultimate career goal. Driven to succeed in his profession and his private life, he has climbed Mount Everest, participated in US sailing championships, and has sailed around the world on several occasions.' },
                { nick: 'Valkyrie', first: 'Meghan J.', last: 'Castellano', place: 'Oceanside, California', birth: 'July 21', age: '31', height: '1.70', weight: '61', side: 'defender', flag: 'us', doc: '“If you don’t constantly feel like you’re being watched, then you aren’t paying attention.” Castellano was born and raised in the quintessential surf community of Oceanside, California. Her father was a respected Colonel in the Marine Corps, her mother a researcher at a nearby biotech company. From an early age, she was known as a high achiever in math and science and as an athletic prodigy. An Olympic hopeful in swimming, Castellano broke her arm in a car accident when she was 16, putting an end to her career. She changed her focus and enlisted in the Navy, while also attending university. After graduating with a degree in Computer Science, specializing in Security and Cryptography, she transferred to the Information Dominance Corps. Castellano’s attention to detail and analytical skill made her one of their most sought-after specialists. She applied to become a SEAL when the position was opened to women and succeeded after several grueling years, acting as encouragement for others to follow.' }
            ]
        },
        {
            id: 'BOPE', color: 'rgb(76, 141, 64)', short: 'BOPE', name: 'Batalhão de Operações Policiais Especiais', doc: 'Rio de Janeiro State\'s Military Police BOPE units have extensive experience in guerilla and urban warfare. Working in the Favelas makes them experts in close quarter combat. BOPE\'s primary focus is supporting local law enforcement in the suppression of crime and drug trafficking.',
            ops: [
                { nick: 'Capitão', first: 'Vicente', last: 'Souza', place: 'Nova Iguaçu, Brazil', birth: 'November 17', age: '49', height: '1.83', weight: '86', side: 'attacker', flag: 'br', doc: '“Focusing only on the bad things in life will keep you from seeing the many opportunities to do good.” The youngest of three children, Souza was raised in Nova Iguaçu, a suburb of Rio de Janeiro. The murder of his older brother by drug dealers prompted Souza to join the Polícia Militar, where he was trained in a wide range of tactical weapons and breaching strategies. During a raid against a crime cartel, Souza was ambushed and taken hostage. Despite the loss of an eye and other brutal treatment, his inner resolve kept him alive for two months before he was rescued. Believing Souza perfectly embodied their motto, Victory over Death, and given his urban warfare experience, Batalhão de Operações Policiais Especiais (BOPE) recruited him into their ranks following his recovery. He has become a renowned expert in the organization and psychological behavior of criminal gangs, and his fight to end drug crime has put a cartel bounty on his head.' },
                { nick: 'Caveira', first: 'Taina', last: 'Pereira', place: 'Rinópolis, São Paulo, Brazil', birth: 'October 15, 1989', age: '31', height: '1.77', weight: '72', side: 'defender', flag: 'br', doc: '“Not every child gets to choose who they grow up to be.” Pereira is seventh of ten kids, born to a widowed mother in a small town of the state of São Paulo. After moving to Rio de Janeiro at a young age, Pereira was arrested for robbery and offered a choice between juvenile reformatory and working with the Polícia Militar as an informant. Years of undercover operations within Brazil’s notorious gangs made her a master of interrogation techniques and surveillance, and Pereira is now frequently called upon to conduct training exercises within the force. Her skills in confined environment tactics, extraction, and extreme risk situations are exemplary. It was Pereira’s actions during the Rio de Janeiro Security Crisis that caught the attention of Rainbow, though multiple reports note that she is considered a dangerous, free-roaming operator. Outside of her professional record, little is known of Pereira’s life, except that she enjoys learning different languages and fighting in unofficial Jiu Jitsu tournaments.' },
            ]
        },
        {
            id: 'SAT', color: 'rgb(154, 39, 62)', short: 'SAT', name: 'Special Assault Teams', doc: 'Officially classified until 1996. Japan\'s Special Assault Team (S.A.T.) has since been collaborating with the S.A.S., GIGN, GSG-9 and FBI SWAT. Comprised of highly trained teams spread throughout Japan, the S.A.T. is a paramilitary counter-terrorism unit.',
            ops: [
                { nick: 'Hibana', first: 'Yumiko', last: 'Imagawa', place: 'Nagoya, Japan', birth: 'July 12', age: '34', height: '1.73', weight: '57', side: 'attacker', flag: 'jp', doc: '“Kyūdō is meditation in action. Explosions are part of that action.” Imagawa is an expert in paramilitary techniques and infiltration of high-risk areas, demonstrating brilliant leadership skills in the field. Encouraged by her family, she has been practicing the long-range martial art of Kyūdō from an early age and possesses the ability to assess multiple factors simultaneously while executing precise, controlled, and fluid motions. Having trained with CTUs around the world including the SAS, FBI SWAT, and GIGN, Hibana has acquired a rare tactical versatility, with proficiency in tubular (bus, train, and airplane) assaults. During her studies at the National Police Academy, she gained the nickname Hibana due to her improvised explosive devices. Fluent in several languages and lethal with any weapon, Imagawa was recruited by the Aichi Prefectural Police Department Special Assault Team, where her diverse techniques and charisma resulted in her to moving quickly up the ranks.' },
                { nick: 'Echo', first: 'Masaru', last: 'Enatsu', place: 'Suginami, Tokyo', birth: 'October 31', age: '36', height: '1.80', weight: '72', side: 'defender', flag: 'jp', doc: '“Don’t ask me what I’m doing on my phone. You don’t want to know.” Enatsu grew up in Suginami, outside of Tokyo. Fascinated with robotics from an early age, he designed and programmed both terrestrial and flying drones and went on to win numerous competitions. After studying Electrical and Electronic Engineering at Tokyo Metropolitan University, Enatsu was encouraged to join the National Police Agency Security Bureau where he worked tirelessly in their research and development lab. Trained in counter-terrorism and intelligence gathering, Enatsu began designing specific tech that would better aid the Bureau. Joint training after the Nagoya hostage crisis prompted Enatsu to transfer to the Aichi Prefectural Police Department Special Unit where his tenacious focus enabled him to find creative solutions and alternate strategies. He eventually returned to Tokyo, where his exceptional intel gathering techniques as well as his quick and unpredictable methodology caught the attention of Rainbow.' }
            ]
        },
        {
            id: 'GEO', color: 'rgb(111, 46, 140)', short: 'GEO', name: 'Grupo Especial de Operaciones', doc: 'The Spanish Grupo Especial de Operaciones (G.E.O.) was founded in 1977 to counter the increasing threat of terror during Spain\'s transition to a Democratic government. Today, the unit prides itself on hostage rescue, disrupting terrorist plots and neutralizing organized crime.',
            ops: [
                { nick: 'Jackal', first: 'Ryad', last: 'Ramírez Al-Hassar', place: 'Ceuta, Spain (Spanish State)', birth: 'February 29', age: '49', height: '1.90', weight: '78', side: 'attacker', flag: 'es', doc: '“You can’t escape me, but that doesn’t mean you won’t try.” Al-Hassar’s early years are unclear due to incomplete foster care records. Eventually released into the care of his older brother, Faisal, the two of them were absent from official records for several years until Faisal’s unsolved murder once again left Al-Hassar without a home. Being guided through the tragedy by a sympathetic police officer solidified Al-Hassar’s resolve to find his brother’s murderer and he joined the Cuerpo Nacional de Policía the day he turned eighteen. Fast-tracked through the academy with the help of his mentor, Al-Hassar stood out as a quick learner with exceptional lateral thinking. His dogged determination resolved a number of criminal investigations but, unfortunately, the case of his brother’s murder remains open. Tagged by the Grupo Especial de Operaciones for further training, Al-Hassar excelled in off-road driving, abseiling, marksmanship, and knowledge of terrorist groups. He is a frequent guest lecturer and part-time instructor at the CNP academy.' },
                { nick: 'Mira', first: 'Elena María', last: 'Álvarez', place: 'Madrid, Spain', birth: 'November 18', age: '39', height: '1.65', weight: '60', side: 'defender', flag: 'es', doc: '“Think of me as your conscience. I see everything, and I’m just as ruthless.” Álvarez is a highly creative operator with the unmatched ability to dominate close-quarters urban environments. Working alongside her father in his auto repair shop helped form her intricate understanding of machinery and prompted her to study mechanical engineering and metallurgy at university. Instilled with a strong sense of justice and an obligation to serve, Álvarez joined the Cuerpo Nacional de Policía. She saw the need for better equipment and developed new bulletproof materials to protect her teammates while on operations. Encouraged to join the Grupo Especial de Operaciones, she beat more than 100 other recruits for the coveted position. The reinforced armor she wears is her design. Álvarez was hired as Rainbow’s Director of Research and Development before being added to the combat roster so that she could better test her developments and improvements under field conditions. She flies helicopters in her spare time.' }
            ]
        },
        {
            id: 'SDU', color: 'rgb(174, 83, 50)', short: 'SDU', name: 'Special Duties Unit', doc: 'Hong Kong\'s Special Duties Unit (S.D.U.) was formed in 1974. Through training with the S.A.S it has become one of the most potent Special Forces units in the world. The S.D.U. handles police and military operations over the sea, air, and land, specializing in anti-terrorism and hostage rescue.',
            ops: [
                { nick: 'Ying', first: 'Siu', last: 'Mei Lin', place: 'Central, Hong Kong (British Hong Kong)', birth: 'May 12', age: '33', height: '1.60', weight: '52', side: 'attacker', flag: 'cn', doc: '“Protecting others is a calling. If you don’t feel it, walk away.” Born in the affluent Central District of Hong Kong, Siu became a close protection operative immediately after high school. Having developed explosive short-range power and combat skills via private tuition, she joined an elite security service with the aim of becoming an all-purpose operative. She traveled to Tel Aviv, Israel, where she spent two years training and serving with the Caracal Battalion, developing an expertise in firearms and combat driving. She returned to Hong Kong, where she joined the police force and then the elite SDU: Flying Tigers. Joint training with the S.A.S. and her creative use of flashbangs earned her the codename, Ying (Firefly). Frequently called upon due to her experience in close protection detail and high-risk operations, Siu is one of the best specialists for operations involving Hong Kong\'s dense urban population.' },
                { nick: 'Lesion', first: 'Liu', last: 'Tze Long', place: 'Junk Bay (Tseung Kwan O), Hong Kong (British Hong Kong)', birth: 'July 2', age: '44', height: '1.74', weight: '82', side: 'defender', flag: 'cn', doc: '“Make no excuses for who you are. Only the weak-minded will demand you make yourself smaller.” Born and raised in Tseung Kwan O (Junk Bay), Liu’s early years were spent working alongside his father in the shipyards, stripping obsolete tankers for raw materials and parts. Growing up surrounded by hazardous materials and seeing their long-term effects on his fellow workers left Liu with an abiding respect for toxins and their effect on the human body. Initially seeking additional income, he volunteered for mine clearing duties in Yunnan and Guangxi provinces where his abilities and bravery caught the attention of key personnel within the Hong Kong Police Department. Liu then joined the Explosive Ordnance Disposal Bureau (EOD), giving him the opportunity to continue his chemistry and forensics-based education along with intense on-site training. Liu’s expertise with chemical, biological, radiological, and nuclear threats made him a clear first pick during the formation of Rainbow’s CBRN unit. Liu continues to volunteer for mine clearing duty in his spare time.' }
            ]
        },
        {
            id: 'GROM', color: 'rgb(84, 157, 155)', short: 'GROM', name: 'Grupa Reagowania Operacyjno-Manewrowego', doc: 'JW GROM was officially activated in 1990, but the elusive unit only went public in 1994. Their namesake is derived from the legendary WWII Silent Unseen. Specialists in unconventional warfare roles, they are famous for leading anti-terrorist operations deep behind enemy lines.',
            ops: [
                { nick: 'Zofia', first: 'Zofia', last: 'Bosak', place: ' Wrocław, Lower Silesia, Poland (Polish People\s Republic)', birth: 'January 28', age: '36', height: '1.79', weight: '72', side: 'attacker', flag: 'pl', doc: '“It isn’t about where you end up, it’s about how you make it home.” Zofia Bosak is the eldest daughter of Jan Bosak, respected former commander of the Polish Special Operation Forces unit, GROM. She excelled in the grueling extracurricular training given by her father, learning diverse techniques including some considered questionable. Zofia’s exceptional attitude saw her pass the GROM selection tests with the highest possible scores. She developed extensive skills beyond hand-to-hand combat and marksmanship, specifically survival, sabotage, target extraction, and field medicine. Driven to be the highest performing soldier in any given unit, Zofia is of singular focus in all of her operations. This focus enabled her to single-handedly evacuate hundreds of civilians, including children, during a rescue mission in Guatemala. She has since earned a number of awards and gained the respect of her commanding officers and peers. Zofia stands out as a lateral thinker with decisive, aggressive operational experience and an impeccable track record both on and off the field.' },
                { nick: 'Ela', first: 'Elżbieta', last: 'Bosak', place: 'Wrocław, Lower Silesia, Poland (Polish People\'s Republic)', birth: 'November 8', age: '31', height: '1.73', weight: '68', side: 'defender', flag: 'pl', doc: '“Together, we can shake the very stars from the sky.” Elżbieta Bosak is the youngest daughter of respected Jan Bosak, former commander of the Polish Special Operations Forces unit GROM. Like her sister, Zofia, Ela excelled in the grueling training imposed upon them by their father. She attended officers’ school but couldn’t reconcile military life with her need for independence and left to study Fine Arts in Berlin. Her reputation for using military paraphernalia in her art attracted the owner of a small private security company, who offered her a job. She was valued in the private sector for her expertise in survivalist tactics and unique adaptive style during protective detail and intelligence gathering, until her father’s death convinced her to return to Poland and join GROM. Ela is a reliable team player with leadership potential, even if her distrust of authority continues to be a point of contention. Her successful collaboration with SEAL prompted her invitation to join Rainbow.' }
            ]
        },
        {
            id: 'SMB', color: 'rgb(196, 206, 207)', short: '707th SMB', name: '707th Special Mission Battalion', doc: 'The 707th Special Mission Battalion was created to protect the 1988 Seoul Olympics. The "White Tigers", named for the revered legend, train in subzero temperatures, engaged in joint peacekeeping operations, maintain an all-female division, and neutralize threats to Korea. Their operators possess black belts in multiple martial arts.',
            ops: [
                { nick: 'Dokkaebi', first: 'Grace', last: 'Nam', place: 'Seoul, South Korea', birth: 'February 2', age: '29', height: '1.69', weight: '62', side: 'attacker', flag: 'kr', doc: '“You say potato, I say botnet.” Nam\'s math and technology skills earned her a National Academic Excellence Scholarship at KAIST (the Korean Advanced Institute of Science and Technology). She served in the Republic of Korea Army (ROK), where her adeptness with technology saw her assigned to the 5163 Army Division. Looking for a chance from office life, Nam earned her place in the 9th Special Forces Brigade, known as the Ghost corps, where she trained in mountaineering, survival techniques, and guerrilla warfare. Highly adaptable, Nam often utilizes a creative, unorthodox approach to gets results. This skill didn’t go unnoticed by the USFK or the 707th Special Mission Battalion. Encouraged to focus on breaching defenses and exploiting weaknesses in networks, Nam was quickly recruited to the 707th and deployed alongside Specialist Chul Kyung Hwa, codename “Vigil,” until their recruitment into Rainbow. Nam works closely with Specialist Masaru “Echo” Enatsu in the R&D lab, engineering new countermeasure technologies.' },
                { nick: 'Vigil', first: 'Chul Kyung', last: 'Hwa', place: 'North Korea', birth: 'January 17', age: '34', height: '1.73', weight: '73', side: 'defender', flag: 'kr', doc: '“Don’t worry about me. I was never here.” Much of Hwa’s early records are unclear. His birth parents remain unknown. What is known is that he suffered the loss of his older brother and father in their bid to reach the Republic of Korea. School records track him from late adolescence, when he was adopted into the Hwa family. Initial reports indicate signs of early trauma – reclusive, slow reader – however, his later grades show great improvement and focus. Hwa gravitated toward electronics and electrical engineering. Wanting to use his talents and demonstrate pride for his country, he chose to join the ROK Navy. He later earned a berth in the ROKN UDT/SEALs, with a knack for radar systems and stealth technology. Handpicked by the respected 707th Special Mission Battalion for unconventional warfare missions, he proved to be quick and lethal. Hwa served together with Specialist Grace “Dokkaebi” Nam until their recruitment into Rainbow.' }
            ]
        },
        {
            id: 'CBRN', color: 'rgb(250, 174, 27)', short: 'CBRN', name: 'Chemical, Biological, Radiological, Nuclear Threat Unit', doc: 'The growing threat of biological and chemical attacks propelled all Special Forces Units to receive training to function under extreme conditions and to handle hazardous materials. Six created the Chemical, Biological, Radiological, Nuclear (CBRN) Threat Unit, formalizing a standard in best practices in the event of such attacks. CBRN operators are experts at handling Level 4 crisis hotzones.',
            ops: [
                { nick: 'Finka', first: 'Lera', last: 'Melnikova', place: 'Gomel, Belarus', birth: 'June 7', age: '27', height: '1.71', weight: '68', side: 'attacker', flag: 'ru', doc: '“The hand you get dealt isn’t the one you have to keep.” Born north of Chernobyl in Gomel, Belarus, Melnikova grew up around people already suffering from birth defects. Driven by her own childhood illness and that of those around her, Melnikova grew up determined to find a cure. She studied Cytology and Genetics at Novosibirsk State University, graduating with a PhD in Molecular Biology. She remained at NSU in the Biotechnology and Virology Laboratory, collaborating remotely with the Research Institute of Fundamental and Clinical Immunology to research treatments for a variety of pathogens and neuropathies, including her own. Melnikova’s ground-breaking research into self-driven monomer motors continues to advance medical science and military technology. Her research directly saved Spetsnaz operators from hazardous materials, resulting in an Order of Honour that opened her eyes to new possibilities. She joined the Army and became the Spetsnaz CBRN Specialist. Melnikova stands out as the go-to biological warfare expert in CTU joint exercises.' },
                { nick: 'Lion', first: 'Olivier', last: 'Flament', place: 'Toulouse, Occitanie, France', birth: 'August 29', age: '31', height: '1.85', weight: '87', side: 'attacker', flag: 'fr', doc: '“Confusing what is right with what is easy can lead down a dangerous path.” When Flament’s rebellious antics landed him in hospital, disowned by his family and on the brink of homelessness, he enlisted with the French Armed Forces in an attempt to gain control of his life. Early reports flagged Flament’s skills and aptitude as well-suited for specific training in CBRN. The additional structure and strict discipline of advanced training allowed him to excel and he was quickly recruited into the 2nd Dragoon Regiment, where he worked primarily with their environmental monitoring sensors. Flament showed a fascination for bacteriology and virology, specifically vector control. Recognizing that his abilities could be better applied elsewhere, he resigned from the army and joined the Gendarmerie, with a view towards the GIGN’s Operational Support Force (FAO). His ability to remain focused and perform precise tasks under stressful conditions caught the attention Specialist Melnikova during a joint mission in Nigeria, who recommended him as a candidate for Rainbow.' }
            ]
        },
        {
            id: 'GIS', color: 'rgb(102, 109, 35)', short: 'GIS', name: 'Gruppo di Intervento Speciale', doc: 'The GIS is headquartered in Livorno and falls under the authority of Comando interforze per le Operazioni delle Forze Speciali (COFS). Both the Ministry of Defense and the Ministry of the Interior can call them into action without a judge\'s approval. Their combat section includes three detachments of four-operative teams. The exploration, reconnaissance, and scouting section uses three operator-teams that include: two fighters, one explorer. They also maintain a sniper/recon team with two snipers and one scout.',
            ops: [
                { nick: 'Alibi', first: 'Aria', last: 'de Luca', place: 'Rome, Italy', birth: 'April 13', age: '45', height: '1.85', weight: '87', side: 'defender', flag: 'it', doc: '“Never reveal the cards you were dealt.” Aria "Alibi" de Luca was born in Tripoli, Libya and immigrated with her family when she was three years old. Her father managed a small ordnance manufacturer, using his extensive North African contacts to open up exports to that region. De Luca earned her understanding and usage of Italian firearms through the family business and training on the shooting range. At 18, Aria entered the European Championships organized by the European Shooting Confederation, and won gold in both the 10-metre running target and 10-metre air pistol divisions. Following the event, a Carabinieri recruiter convinced her to join the police force. De Luca’s precision shooting skills and professionalism shot her up the ranks quickly, and she served for a time with the elite Raggruppamento Operativo Speciale in fighting organized crime. She eventually earned a spot in the prestigious Gruppo Intervento Speciale (G.I.S.), and following a successful operation in Afghanistan despite being separated from her unit, she was singled out for undercover work in organized crime. She infiltrated the Vinciguerra Crime Family as an arms dealer and spent several years among them before bringing them down from the inside. A newspaper leak of impending operations against the Vinciguerras then forced the G.I.S. to accelerate their initiative. Following her undercover work and the successful dismantling of the Vinciguerra Crime Family, Aria de Luca received the invitation to join Rainbow as a capable operator.' },
                { nick: 'Maestro', first: 'Adriano', last: 'Martello', place: 'Tripoli, Libya (Libyan Arab Jamahiriya)', birth: 'December 15', age: '37', height: '1.71', weight: '63', side: 'defender', flag: 'it', doc: '“Did I ever tell you about the time we tree-jumped into a Congo swamp at night? No? Oh, it’s a good one.” Adriano "Maestro" Martello, oldest in a family of eight children, grew up in Rome, but attended the Military Academy of Modena at 18. He joined the Carabinieri and earned a spot as an Explorer Paratrooper in the 1st Paratrooper Regiment known as Tuscania. After several distinguished tours where he earned Silver and Bronze Medals of Military Valor, Martello qualified for Gruppo di Intervento Speciale (Special Intervention Group or G.I.S.) and participated in joint operations in Iraq, earning a facial scar from a roadside IED. He engaged in multiple actions against homegrown threats in Italy and eventually became an instructor helping train Tier 3 units in the Italian military. After Martello’s tour was completed, he went into private consultation where his courses quickly became a top-rated operator bootcamp for teaching advanced techniques to Tier 3 and Tier 2 units, as well as private military companies. The Tuscania eventually convinced Martello to re-enlist to help upgrade one of their units to a Tier 2 Special Forces classification, and this enabled him to join Rainbow as a representative of the Italian Units.' }
            ]
        },
        {
            id: 'THEUNIT', color: 'rgb(111, 128, 143)', short: 'THE UNIT', name: 'Delta Force', doc: 'The 1st Special Forces Operational Detachment-Delta (1st SFOD-D), commonly referred to as Delta Force, is an elite special mission unit of the United States Army, under operational control of the Joint Special Operations Command. The unit is tasked with specialized missions primarily involving hostage rescue and counterterrorism, as well as direct action and special reconnaissance against high-value targets.',
            ops: [
                { nick: 'Maverick', first: 'Erik', last: 'Thorn', place: 'Boston, Massachusetts', birth: 'April 20', age: '36', height: '1.80', weight: '82', side: 'attacker', flag: 'us', doc: '“The Devil’s in the details… that’s where you’ll find me.” Bostonian Erik Thorn came from a multilingual home and ranked in the top 2% in intelligence. After high school, he enlisted with the U.S. Army and rose in rank over a short period of time. He learned Dari and became an Intelligence Officer, serving in Kabul as foreign reporters, adventurers, and criminals flocked to the city. Thorn was well known in the underground club circuit, and even among locals as a proficient Buzkashi player. Thorn was invited into the Unit as their regional specialist. Following selection, he remained in country, gathering intel, building networks of allies and safe houses, and tracking hostiles. As the situation in Kabul worsened, Thorn kept tabs on Americans, rescuing them when necessary and helping locals escape the violence. He was investigating a missing reporter when The Unit lost contact with him. After two years of silence, he re-emerged with enough intel to dismantle a major insurgency operation. There were still questions regarding his disappearance, but he was exonerated and his testimony sealed. His successful missions, along with his expertise, gained him the attention of Six.' }
            ]
        },
        {
            id: 'MPS', color: 'rgb(111, 128, 143)', short: 'MPS', name: 'Grim Sky Urban Tactical Response Team', doc: 'The Metropolitan Police Service (MPS), better known by their metonym, Scotland Yard, is a territorial police force responsible for policing most of London. The MPS also has significant national responsibilities, such as coordinating and leading on UK-wide national counter-terrorism matters, and the protection of the senior members of the British Royal Family, and also members of The Cabinet and other ministerial members of Her Majesty\'s Government.',
            ops: [
                { nick: 'Clash', first: 'Morowa', last: 'Evans', place: 'London, England', birth: 'June 7', age: '35', height: '1.79', weight: '73', side: 'defender', flag: 'gb', doc: '“Come closer. I dare you.” Morowa Evans led the fight in her community against racist groups in often-violent clashes. She was relentless until the day her friend and mentor, Tray Pearson, died trying to stop looters during a riot. Two months later, Evans offered her assistance to the Metropolitan Police Service (MPS) because she wanted to make a difference from within the system. The MPS offered her a clean slate if she helped stop protests from going violent. Evans made it her career, going from insider to eventually joining the MPS. During the 2011 London Riots, Police Constable Evans commanded the front line in the Territorial Support Group to stop the violence from spreading, and later acquired special permission to attend Gold Command meetings, devising new crowd-control strategies based on her years as riot leader. PC Evans made 274 arrests throughout her service and later made Detective Constable. She earned the Queen’s Police Medal for exceptional bravery and earned a spot in Rainbow due to her experience, service record, and tenacity.' }
            ]
        },
        {
            id: 'GSUTR', color: 'rgb(111, 128, 143)', short: 'GSUTR', name: 'Grim Sky Urban Tactical Response Team', doc: 'The Urban Tactical Response Team, codenamed Grim Sky (or GSUTR) is Rainbow\'s testbed for operations in dense urban centers. It draws on such expertise as riot-officers for mob behavior and intelligence operators for converting local assets and building allied networks. The core operators are Maverick and Clash, but the unit also employs the expertise of Caveira, Bandit, Alibi, Castle, and Ying. Grim Sky trains operators on navigating and surviving in hostile cities or evading and diverting mobs.',
            ops: [
                { nick: 'Maverick', first: 'Erik', last: 'Thorn', place: 'Boston, Massachusetts', birth: 'April 20', age: '36', height: '1.80', weight: '82', side: 'attacker', flag: 'us', doc: '“The Devil’s in the details… that’s where you’ll find me.” Bostonian Erik Thorn came from a multilingual home and ranked in the top 2% in intelligence. After high school, he enlisted with the U.S. Army and rose in rank over a short period of time. He learned Dari and became an Intelligence Officer, serving in Kabul as foreign reporters, adventurers, and criminals flocked to the city. Thorn was well known in the underground club circuit, and even among locals as a proficient Buzkashi player. Thorn was invited into the Unit as their regional specialist. Following selection, he remained in country, gathering intel, building networks of allies and safe houses, and tracking hostiles. As the situation in Kabul worsened, Thorn kept tabs on Americans, rescuing them when necessary and helping locals escape the violence. He was investigating a missing reporter when The Unit lost contact with him. After two years of silence, he re-emerged with enough intel to dismantle a major insurgency operation. There were still questions regarding his disappearance, but he was exonerated and his testimony sealed. His successful missions, along with his expertise, gained him the attention of Six.' },
                { nick: 'Clash', first: 'Morowa', last: 'Evans', place: 'London, England', birth: 'June 7', age: '35', height: '1.79', weight: '73', side: 'defender', flag: 'gb', doc: '“Come closer. I dare you.” Morowa Evans led the fight in her community against racist groups in often-violent clashes. She was relentless until the day her friend and mentor, Tray Pearson, died trying to stop looters during a riot. Two months later, Evans offered her assistance to the Metropolitan Police Service (MPS) because she wanted to make a difference from within the system. The MPS offered her a clean slate if she helped stop protests from going violent. Evans made it her career, going from insider to eventually joining the MPS. During the 2011 London Riots, Police Constable Evans commanded the front line in the Territorial Support Group to stop the violence from spreading, and later acquired special permission to attend Gold Command meetings, devising new crowd-control strategies based on her years as riot leader. PC Evans made 274 arrests throughout her service and later made Detective Constable. She earned the Queen’s Police Medal for exceptional bravery and earned a spot in Rainbow due to her experience, service record, and tenacity.' }
            ]
        },
        {
            id: 'GIGR', color: 'rgb(168, 131, 79)', short: 'GIGR', name: 'Groupe d\'Intervention de La Gendarmerie Royale', doc: 'GIGR (Groupe d\'Intervention de La Gendarmerie Royale) is a regiment consisting of specialized military units within the Royal Moroccan Gendarmerie. Their base of operations and missions have been kept top secret, while part of their special training has involved dealing with extremist ideologies and negotiation tactics. Their primary function: dismantle insurgent operations and intervene in emergency crises.',
            ops: [
                { nick: 'Nomad', first: 'Sanaa', last: 'El Maktoub', place: 'Marrakesh, Morocco', birth: 'July 27', age: '39', height: '1.71', weight: '63', side: 'attacker', flag: 'ma', doc: '“Deep down in my veins, I knew I had to travel. Now that I have, I’m certain I haven’t travelled enough.” Brought up in a wealthy Moroccan family, Sanaa El Maktoub travelled considerably at a young age, visiting Europe and North Africa, and dreaming about braving remote regions. She enlisted in the military at 19 and later joined the Groupe d\'Intervention de La Gendarmerie Royale (GIGR) after graduating from the legendary Fortress. She served 4 tours with the Mountain Infantry Battalion and took part in Flintlock exercises and joint missions with Trans-Saharan Counterterrorism Initiative partners. She became her unit’s expert on environmental operations. Between tours, she undertakes solo expeditions. El Maktoub is among the few explorers who can cross the Sahara, climb up the Alps, trek through Asia’s rainforests, march along the Arctic Circle… and still return to her unit in operational shape. Rain or shine, desert or polar climates, she can walk through it all. Perceptive and resourceful, she’s an expert survivalist who sketches out her trips in her notebook.' },
                { nick: 'Kaid', first: 'Jalal', last: 'El Fassi', place: 'Aroumd, Morocco', birth: 'June 26', age: '58', height: '1.95', weight: '98', side: 'defender', flag: 'ma', doc: '“Lead by example and the mountain will move.” Jalal El Fassi was raised on stories of the Fortress, the legendary training facility in the Atlas Mountains. Its incomparable reputation, along with its famed “Kaids” (Commander) were seared into El Fassi. He joined the GIGR (Royal Moroccan Gendarmerie) at 18, demonstrating natural leadership skills under fire. His ability to effectively command specialized squadrons in joint Trans-Saharan Counterterrorism Initiative (TSCTP) operations led to his promotion as Captain. After years of service, the Fortress’ reigning Commander chose his successor: El Fassi, whose authoritative but ethical style made him a worthy “Kaid”. His imposing presence and strict values led to success with his graduates, and the Fortress quickly gained accolades. He further proved its excellence through the thousands of soldiers who trained or taught on its grounds. Over years of negotiating, he welcomed troops from across Africa and the Middle-East, fostering stronger ties between TSCTP members and African Standby Force countries.' },
                { nick: 'Oryx', first: 'Saif', last: 'Al Hadid', place: 'Azraq, Zarqa, Jordan', birth: 'July 3', age: '45', height: '1.95', weight: '130', side: 'defender', flag: 'jo', doc: '“Sometimes, the only way out is through.” Little is known about Al Hadid’s life. He grew up in a small town adjacent to an air force base, and by all accounts had a normal childhood up until he disappeared from international records for more than fifteen years. He eventually resurfaced in Jordan, but stayed only long enough to obtain a new passport. He learned wrestling in Istanbul, Muay Thai in Bangkok, tactical driving in Berlin, and precision marksmanship in Damascus, likely working for a paramilitary sponsor. Then he disappeared again. He next showed up as a cadet at Jalal “Kaid” El Fassi’s Fortress. As the years passed, his role evolved, from recruit to steward to instructor. Now the unofficial second-in-command, Al Hadid maintains the Fortress during Kaid’s absences and acts as a trusted advisor whenever the two of them are together. Rumors of Al Hadid’s ferocity abound, but remain uncorroborated by field reports and should be disregarded.' }
            ]
        },
        {
            id: 'SASR', color: 'rgb(207, 1, 88)', short: 'SASR', name: 'Special Air Service Regiment', doc: 'The Special Air Service Regiment (SASR or SAS) shares the name of the unit that inspired its creation back in 1957. This Australian Army\'s Special Forces unit consists of 4 Sabre Squadrons and specialists at counter-insurgency operations,special reconnaissance,counter-terrorism,mobility operations,unconventional warfare and hvt manhunting operations.',
            ops: [
                { nick: 'Gridlock', first: 'Tori', last: 'Tallyo Fairous', place: 'Longreach, Central Queensland, Australia', birth: 'August 5', age: '36', height: '1.77', weight: '102', side: 'attacker', flag: 'au', doc: '“You’ve gotta have a couple of roos loose in the top paddock to sign up for this life, but there’s nowhere I’d rather be.” The eldest of five, Fairous has demonstrated leadership potential throughout her life. From an early age Fairous worked with engines and competed in robot championships. Her mechanic background was heavily influenced by her father, a military aircraft mechanic. Fairous joined the Australian army reserves to further develop her mechanical engineering skills and to have access to the best equipment. After graduating from university she chose Army branch of the Australian Defense Force, where she honed her mechanical prowess. Fairous also has expertise in a range of weapons, intelligence gathering and close protection duties, and has the ability to adapt to unexpected situations and remain calm in dangerous situations. This unique skill set made her an essential recruit into the SASR Mobility Platoon. Fairous was awarded the National Emergency Medal for her part in saving firefighters. She has been offered lead positions but has repeatedly turned them down.' },
                { nick: 'Mozzie', first: 'Max', last: 'Goose', place: 'Portland, Victoria, Australia', birth: 'February 15', age: '35', height: '1.62', weight: '64', side: 'defender', flag: 'au', doc: '“C’mon, I\'m not here to fuck spiders.” Right after Year 10, Max Goose applied to enter the Australian Defence Force Academy, later working in Combat & Security. He joined an infantry regiment that incorporated dirt bikes and all-terrain vehicles in their reconnaissance operations. Goose excelled in land navigation and became the two-wheeler expert in raids, scouting, and convoy operations. Following Operation Catalyst, he was handpicked to join the Special Air Service Regiment (SASR), so long as he passed selection and refrained from talking back. His specialized off-road skillsets and quick thinking were highly prized, even though his driving style appeared reckless. He deployed to Operation Slipper and served until the operation’s conclusion. He later received the National Emergency Medal for saving firefighters during the Esperance bushfires. Goose is a calculated daredevil who loves testing upcoming military stealth bikes, but he says there’s no bigger honor than being asked to join Rainbow Six.' }
            ]
        },
        {
            id: 'JAEGERCORPS', color: 'rgb(46, 62, 134)', short: 'JAEGER CORPS', name: 'Jægerkorpset', doc: 'Denmark\'s Jægerkorpset (Jaeger Corps) was minted in the early Sixties as a Cold War unit since turned counter-terrorism specialists. They are specialized in long-range reconnaissance and parachuting, as well as counter-terrorism, combat swimming, and demolitions to name a few of their skills. They have served with distinction alongside the U.S. Navy SEALS and British SAS.',
            ops: [
                { nick: 'Nøkk', first: '[REDACTED]', last: '', place: '[REDACTED]', birth: '[REDACTED]', age: '[REDACTED]', height: '[REDACTED]', weight: '[REDACTED]', side: 'attacker', flag: 'dk', doc: '“The only thing I feel when I pull the trigger is recoil.” For reasons of National Security and currently active missions, Nøkk’s records are sealed at NATO Confidential security clearance, but her files have been released to Six. Nøkk enlisted at the Army NCO School in Sønderborg, then enrolled at the Royal Danish Military Academy where she graduated at the rank of First Lieutenant. With four deployments under her belt, Nøkk underwent additional special operations training, earning her Jægerkorpset maroon beret with skills in covert ops, combat search and rescue, direct action, special recon, arctic warfare, and advanced breaching. Nøkk served in Afghanistan and Iraq, often alone in deep undercover behind enemy lines. She received commendations for eliminating hostile insurgents in surgical strikes and was responsible for uncovering Erik “Maverick” Thorn’s location, forwarding that intel to the Unit. Nøkk keeps her identity hidden from all but her fellow operators. NATO’s O&P division recommended Nøkk for Rainbow as one of its deep cover specialists.' }
            ]
        },
        {
            id: 'SECRETSERVICE', color: 'rgb(46, 62, 134)', short: 'SECRET SERVICE', name: 'U.S. Secret Service', doc: 'The U.S. Secret Service (or simply Secret Service) is a Federal Law Enforcement Agency formed in 1865 to investigate counterfeiting during the American Civil War. The Secret Service has the dual role of protecting its nation\'s leaders as well as safeguarding the U.S. financial infrastructure. Since 2003, they have been under the aegis of the Department of Homeland Security.',
            ops: [
                { nick: 'Warden', first: 'Collinn', last: 'McKinley', place: 'Louisville, Kentucky', birth: 'March 18', age: '48', height: '1.83', weight: '80', side: 'defender', flag: 'us', doc: '"I\'m never unprepared." Collinn McKinley enrolled in the Marine Corps at 18 and earned several commendations in his service jacket for his aggressive quick-thinking, achieving Master Sergeant despite a few minor infractions on his record. After his third tour, he left the Marines and entered the Secret Service in close-protection detail. McKinley’s agility was instrumental in saving Secretary of State Baldwin’s life when insurgents attacked the U.S. diplomatic junket. Baldwin later went on to win the U.S. Presidential and requested McKinley be assigned to the Presidential Protective Division. McKinley has spent over a decade in Washington, protecting important political figures. He is the foremost expert in close protection detail, and with President Baldwin finishing his second term, McKinley has received high endorsements for his transition into Rainbow.' }
            ]
        },
        {
            id: 'APCA', color: 'rgb(17, 87, 7)', short: 'APCA', name: 'Asociación de Patrimonio Cultural Arqueológico', doc: 'The Asociación de Patrimonio Cultural Arqueológico (lit. Archaeological Cultural Patrimony Association) or APCA is a paramilitary Anti Archaeological Looting organization in Peru. It was established by Azucena Rocío "Amaru" Quispe.',
            ops: [
                { nick: 'Amaru', first: 'Azucena Rocío', last: 'Quispe', place: 'Cojata, Puno, Peru', birth: 'May 6', age: '48', height: '1.89', weight: '84', side: 'attacker', flag: 'pe', doc: '“Forget who you are, and nothing else matters. You’ll fight for anyone, and never know why.” Specialist Azucena Rocío “Amaru” Quispe began her career as an anthropologist concerned with the preservation of Peru’s shared cultural heritage. Her unique familial link to colonial explorers of the early 20th century gave her uncommon insight into both how voyages of discovery can shape cultural consciousness, and into the deep and abiding loss created when a shared cultural touchstone is lost. She served for several years in the Policía Nacional del Perú (PNP), before reorienting as a freelance archeologist focussed on the discovery and categorisation of new archaeological sites. After several run-ins with antiquities traffickers, and failed attempts to bring them down from within, she turned to guerrilla tactics in order to seize important cultural discoveries for the Peruvian State. When Specialist César “Goyo” Ruiz Hernández made us aware of her presence, she had already spent some 20-odd years in the jungles of Peru, fighting the cartels on her own terms.' }
            ]
        },
        {
            id: 'FES', color: 'rgb(17, 87, 7)', short: 'FES', name: 'Fuerzas Especiales', doc: 'The Fuerzas Especiales (Special Forces), also known as FES (the initials of their motto, Fuerza, Espíritu, Sabiduría), is a Special forces unit of the Mexican Navy officially established in late 2001.',
            ops: [
                { nick: 'Goyo', first: 'César Ruiz', last: 'Hernández', place: 'Culiacán Rosales, Sinaloa, Mexico', birth: 'June 10', age: '31', height: '1.71', weight: '83', side: 'defender', flag: 'mx', doc: '“A person is never more honest than when they think they’re alone.” César Ruiz Hernández was eleven years old when a bomb destroyed his home, killing his father and sister and severely injuring his mother. With the help of Specialist Azucena Rocío “Amaru” Quispe, César’s mother Sofia taught him to observe his surroundings, and to avoid the other boys his age who had been drawn into gang-related affairs. She encouraged him to enroll at the Heroic Naval Military School, where he graduated as a teniente de corbeta. He joined the Naval Infantry, then the Amphibious Commando Battalion, participating extensively in anti-smuggling operations and several high-profile arrests. Becoming a member of the Fuerzas Especiales introduced him to the reality that drugs were no longer the primary source of income for the cartels. He began working with UNESCO and INTERPOL to combat antiquities trafficking, where he gained the attention of Rainbow as a mind with a keen tactical sense and exceptional forward-thinking.' }
            ]
        },
        {
            id: 'NIGHTHAVEN', color: 'rgb(45, 198, 210)', short: 'NIGHTHAVEN', name: 'NIGHTHAVEN Private Military Company', doc: 'NIGHTHAVEN is a Private Military Company that was founded and is currently led by Jaimini Kalimohan Shah.',
            ops: [
                { nick: 'Kali', first: 'Jaimini Kalimohan', last: 'Shah', place: 'Amreli, Gujarat, India', birth: 'August 21', age: '34', height: '1.70', weight: '67', side: 'attacker', flag: 'in', doc: '“Acceptance of mediocrity is the first step toward failure.” Born to wealthy parents, Shah’s ability to achieve her goals was assured from an early age. This self-assurance hit a brick wall when she tried to join the military. Her interest in martial arts led her to enlist, but she quickly discovered that women weren’t allowed to serve in combat units. Despite all of her money and all of her social influence, she had found an obstacle between her and something she wanted, and it would not budge. Leaving the military, she created her own Private Security Company to operate within India’s borders, then a Private Military Company, NIGHTHAVEN, to operate overseas. She routinely negotiates multi-million-dollar contracts with incredibly favorable terms. Her ruthlessness is legendary, but by becoming a resource the Indian government desperately needs she has circumvented the laws that kept her from her goal and revalidated her self-perception as an unstoppable force in a largely static world.' },
                { nick: 'Wamai', first: 'Ngũgĩ Muchoki', last: 'Furaha', place: 'Lamu, Kenya', birth: 'June 1', age: '28', height: '1.87', weight: '83', side: 'defender', flag: 'ke', doc: '“The closer you are to death, the more vibrant life becomes.”. Born to a fishing family on the coast of Kenya, Furaha spent his childhood hunting sharks and collecting lost treasures from the ocean floor of the Lamu Archipelago. It soon became apparent that he was able to stay underwater far longer than his peers, and medical exploration revealed an abnormal physiology that contributed to Furaha’s long-held belief that he was “not from here.” When the opportunity arose to join the Kenyan Navy, and later the Kenya Special Boat Unit, he put his skills to good use. He quickly drew the attention of generals within the navy as well as the worldwide scientific community for his prolific and frequent record-breaking freedives. He later transitioned to NIGHTHAVEN, drawn by the promise of more down-time and a private boat to take him to where his next dive site might be.' },
                { nick: 'Ace', first: 'Håvard', last: 'Haugland', place: 'Lærdalsøyri, Vestland, Norway', birth: 'March 15', age: '33', height: '1.87', weight: '75', side: 'attacker', flag: 'no', doc: '“The perfect shot, like the perfect rescue, is all about the framing.” Born in a quiet but historic village, Haugland benefited early on from high praise and a lack of competition. Consistently the best at whatever he set his mind to, he easily imagined himself as an admired pediatric surgeon and enrolled in medical school. However, he soon discovered that memorizing theory wasn’t to his liking and instead opted for paramedic training in order to get into the action more quickly. The Norwegian Armed Forces brought him into a new world of achievement. He completed basic training and joined the Norwegian Home Guard, where he acquired a reputation for heroics. After completing his service obligation, he was accepted into the Forsvarets Spesialkommando and took part in a prominent hostage rescue soon afterward. As part of a joint UN operation in Somalia, his tendency toward theatrics and his impulsive nature resulted in him saving Kali’s life. The offer to join NIGHTHAVEN swiftly followed.' },
                { nick: 'Aruni', first: 'Apha', last: 'Tawanroong', place: 'Ta Phyraya, Sa Kaeo, Thailand', birth: 'August 9', age: '42', height: '1.60', weight: '58', side: 'defender', flag: 'th', doc: '“In every conflict, it’s the children who are made to suffer, even after the fighting has stopped.” As a private detective, her discovery of a bomb plot in Bangkok brought Aruni to the attention of the Royal Thai Police (RTP). Her knack for connecting the dots between seemingly-unrelated incidents earned her grudging respect from Thailand’s male-dominated law enforcement agencies, as well as hostility from numerous criminal syndicates. The RTP offered Aruni a Detective position with the Crime Suppression Division, where she dismantled a human trafficking ring and foiled no fewer than four bomb plots. Her ability to track and connect diverse shipments of explosive materials was lauded by her superiors. Unfortunately, Aruni’s police career ended when she was nearly killed during an operation in Bangkok. Following her recovery, Aruni was approached by Jaimini “Kali” Shah. Kali’s access to cutting-edge prosthetics was likely a factor in Aruni’s decision to join Nighthaven.' }
            ]
        },
        {
            id: 'REU', color: 'rgb(149, 108, 149)', short: 'REU', name: 'REU organization', doc: 'The REU is a space development organization in Europe',
            ops: [
                { nick: 'Iana', first: 'Nienke', last: 'Meijer ', place: 'Katwijk, the Netherlands', birth: 'August 27', age: '35', height: '1.57', weight: '56', side: 'attacker', flag: 'nl', doc: '"All systems are complementary, if you know how to connect them.” Meijer’s mother was lead engineer on the Huygens Atmospheric Structure Instrument that landed on Titan. Encouraged to reach for the stars from an early age, she studied Aerospace Engineering with a view toward becoming a fighter pilot. Unfortunately, her albinism meant she had compromised retina and her application was refused. She changed her focus to systems engineering, developing contact lenses that overcorrected her genetic deficit while integrating a state-of-the-art AR overlay. It was a collaboration during her doctorate that gave Meijer the first taste of where she longed to be. Returning from the International Space Station only fuelled her desire to explore the farthest reaches of the cosmos, no matter the cost. She pioneered topographical mapping software that allows her to project a real-time, virtual copy of herself to anywhere visible by satellite or drone. It was this technology which caught the eye of Elena “Mira” Álvarez, and subsequently Six.' }
            ]
        },
        {
            id: 'ITF', color: 'rgb(74, 142, 156)', short: 'ITF', name: 'Inkaba Task Force', doc: 'The Inkaba Task Force Anti-Poaching Unit (ITF) is an conservation group based in South Africa. Founded in 2008, it is led by Thandiwe Ndlovu',
            ops: [
                { nick: 'Melusi', first: 'Thandiwe', last: 'Ndlovu', place: 'Louwsburg, KwaZulu-Natal, South Africa', birth: 'June 16', age: '32', height: '1.72', weight: '68', side: 'defender', flag: 'za', doc: '“Understanding is the only tool that vanquishes ignorance.” Born in the small town of Louwsburg near the Ithala Game Reserve, Ndlovu spent many years exploring with her friend, Elna Gardiner. As they grew, so did their appreciation of and sense of responsibility for the animals on the reserve. The threat from poachers fueled their determination, and though haunted they focused on the lives they could save, rather than past casualties. Ndlovu signed up with the South African National Defence Force to broaden her skillset and fund her field ranger training. Her persistence and dedication brought her to the attention of the 1 Parachute Battalion, until an ambush in the Central African Republic left her badly wounded. When Gardiner, who had become an accomplished veterinarian, asked for help defending Hluhluwe–Imfolozi Park, Ndlovu resigned from the military and began training local women in tracking, interception, and surveillance. Together, they are the heart of the Inkaba Task Force Anti-Poaching Unit.' }
            ]
        },
        {
            id: 'ROS', color: 'rgb(112, 177, 60)', short: 'ROS', name: 'Rainbow Operation Staff', doc: 'The Rainbow Operation Staff is a training division of Team Rainbow',
            ops: [
                { nick: 'Zero', first: 'Samuel Leo', last: 'Fisher', place: 'Baltimore, Maryland', birth: 'August 8, 1957', age: '63', height: '1.78', weight: '77', side: 'attacker', flag: 'us', doc: '“Prepare, execute, vanish.” Though the CIA and Third Echelon have classified the majority of Fisher’s childhood it is known he was born in the Baltimore suburb of Towson, Maryland, where he was raised by his paternal grandmother, Sarah. He was enrolled in a Military Boarding School where he learned to focus his energy, hone his skills, and to either follow orders or be sure to hide the evidence. From school Fisher enrolled directly in the United States Naval Academy where he majored in Political Science and later went on to pursue SEALs Training. While serving in the Persian Gulf, Bolivia, Columbia, Senegal, and Kosovo, Fisher became known for his ability to complete the mission, regardless of personal cost. After being awarded a Defense Distinguished Service Medal, Fisher spent time as an instructor at Little Creek Naval Base, Virginia. He was recruited to the CIA, where he [REDACTED].' }
            ]
        },
        {
            id: 'FBI', color: 'rgb(140, 0, 0)', short: 'FBI', name: 'Federal Bureau of Investigation', doc: 'The Federal Bureau of Investigation (FBI) is the domestic intelligence and security service of the United States and its principal federal law enforcement agency. Operating under the jurisdiction of the United States Department of Justice, the FBI is also a member of the U.S. Intelligence Community and reports to both the Attorney General and the Director of National Intelligence. A leading U.S. counter-terrorism, counterintelligence, and criminal investigative organization, the FBI has jurisdiction over violations of more than 200 categories of federal crimes. Although many of the FBI\'s functions are unique, its activities in support of national security are comparable to those of the British MI5 and the Russian FSB. Unlike the Central Intelligence Agency, which has no law enforcement authority and is focused on intelligence collection abroad, the FBI is primarily a domestic agency, maintaining 56 field offices in major cities throughout the United States, and more than 400 resident agencies in smaller cities and areas across the nation. Despite its domestic focus, the FBI also maintains a significant international footprint, operating 60 Legal Attache (LEGAT) offices and 15 sub-offices in U.S. embassies and consulates across the globe. The FBI can and does at times carry out secret activities overseas, just as the CIA has a limited domestic function.',
            ops: [
                { nick: 'Flores', first: 'Santiago Miguel', last: 'Lucero', place: 'Buenos Aires, Argentina (El Proceso)', birth: 'October 2', age: '38', height: '1.81', weight: '72', side: 'attacker', flag: 'us', doc: '“In life, you have to commit to the things that make you happy. For me, that’s robbing the rich and corrupt.” Providing for his mother as her health slowly declined, Lucero was unfulfilled with work in the public sector and unimpressed with military school. This drew him to burglary as an occupation, and he found purpose in robbing powerful criminals to give back to the poor. Operating in the Flores district of Buenos Aires, Lucero’s notoriety grew and he came to be known as ‘the Man from Flores.’ When his identity was exposed and he had to flee, Specialist Eliza “Ash” Cohen offered him asylum in the United States. In exchange, he provided evidence against Buenos Aires’ most ruthless crime lords. With a new life in Los Angeles, Lucero opened his own food truck from which he operated heists for five years. When Cohen became aware of his activities, she offered him a seat at her table, and a stable future in which he could build a family.' }
            ]
        },
        {
            id: 'RAINBOW', color: 'grey', short: 'RAINBOW', name: 'Team Rainbow Recruits', doc: 'Team Rainbow (also known as RAINBOW) is an elite international counterterrorist unit that falls under the direct supervision of NATO. The unit was formed to combat terrorist actions worldwide in a more effective way by assembling a team of elite counterterrorist operatives from nations all over the world. Since its formation in 1999, Rainbow has prevented several terrorist plots since its activation but was deactivated in 2012. The unit was reactivated three years later under a new director codenamed "Six", to combat the White Masks and their widespread terrorist attacks.',
            ops: [
                { nick: 'Recruit', flag: 'nato', doc: 'A Highly Customizable Operator, the Recruit varies between equipment from the five base-game CTUs. As such, the Recruit brings more versatility than any other Operator, but lacks the ability to properly specialize in any particular role.' }
            ]
        }
    ]
}
